const app=document.querySelector('#app');
app.innerHTML=`<section class="intro"><div class="intro-copy"><div class="eyebrow">A TINY ASK</div><p lang="ru">Говорят, Роналду забил далеко не каждый удар, который наносил по воротам.</p><p lang="ru">А мы попробовали всего один раз.</p><p lang="ru">Кажется, статистически рано делать выводы.</p><h1><span>Why not </span><span>try again?</span></h1><div class="intro-bottom"><button class="primary" id="begin">ONE MORE SHOT</button><span class="micro">a little courage.<br>another chance.</span></div></div><aside class="number-art" aria-hidden="true"><div class="art-top"><span>SECOND ATTEMPT</span><span>EST. 2026</span></div><div class="big-number">002</div><div class="art-middle"><span>Worth another shot.</span><div class="stamp">TO BE CONTINUED</div></div><div class="art-bottom"><span>ONE INVITATION.<br>TWO PEOPLE.</span><span class="barcode"></span><span>ADMIT<br>TWO</span></div></aside></section>`;

import {MAIN,SECOND,MUSIC,DATES,TIMES,initialState,normalize,activity,hasDrive,competitive,cleanup,steps,displayDate,displayTime,validateStep,validatePlan} from './model.js';
import {SUBMISSION_ENDPOINT} from './config.js';
const introHTML=app.innerHTML;
const state=initialState();
let current='intro',busy=false,submissionId='',lastPayload='',failed=false;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={main:['MAIN EVENT','BUILD OUR DATE','Pick the main event.'],second:['SECOND STOP','ONE MORE?','One stop is enough...\nbut two sounds better.'],music:['THE SOUNDTRACK','ONE IMPORTANT QUESTION.','Who controls the music?'],date:['SAVE THE DATE','WHEN?','Four days. One good reason to make time.'],time:['THE DETAILS','WHAT TIME?','Let’s find our moment.'],pickup:['THE MEETING POINT','WHERE SHOULD I PICK YOU UP?','Address, landmark, café — whatever is easiest.'],review:['THE PLAN','SO, WE HAVE A PLAN.','A second attempt. Entirely our own.']};
function choice(field,value,label,desc='',extra='',className=''){const selected=state[field]===value;return `<button type="button" class="choice ${className}" data-field="${field}" data-value="${value}" aria-pressed="${selected}"><span class="name">${esc(label)}</span>${extra}${desc?`<span class="desc">${esc(desc)}</span>`:''}<span class="check" aria-hidden="true">${selected?'✓':''}</span></button>`;}
function cards(field,options){return `<div class="choices">${options.map(([v,l,d])=>choice(field,v,l,d,'',v==='none'?'wide':'')).join('')}</div>`;}
function field(key,label,placeholder='',type='text',max=120){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" name="${key}" type="${type}" value="${esc(state[key])}" placeholder="${placeholder}" maxlength="${max}" autocomplete="off" ${type==='text'?'spellcheck="false"':''} aria-describedby="error" required></div>`;}
function review(){const rows=[];rows.push([state.secondActivity==='none'?'PLAN':'MAIN',activity(state,'main'),'main']);if(state.secondActivity!=='none')rows.push(['THEN',activity(state,'second'),'second']);rows.push(['DATE',displayDate(state.date),'date'],['TIME',displayTime(state),'time']);if(hasDrive(state))rows.push(['MUSIC',MUSIC.find(x=>x[0]===state.music)?.[1]||'','music']);rows.push(['PICKUP',state.pickup,'pickup']);return `<dl class="review">${rows.map(([label,value,step])=>`<div class="review-row"><dt>${label}</dt><dd>${esc(value)}</dd><button class="edit" data-edit="${step}" aria-label="Edit ${label.toLowerCase()}">EDIT</button></div>`).join('')}</dl>`;}
function content(){switch(current){case 'main':return cards('mainActivity',MAIN)+(state.mainActivity==='custom'?field('mainActivityCustom',"What's your idea?",'Something you’d love to do...'):'');case 'second':return cards('secondActivity',SECOND.filter(([v,l])=>v==='custom'||normalize(l)!==normalize(activity(state,'main'))))+(state.secondActivity==='custom'?field('secondActivityCustom',"What's your idea?",'One more good idea...'):'');case 'music':return cards('music',MUSIC);case 'date':return `<div class="choices dates">${DATES.slice(0,4).map((d,i)=>choice('date',d,['FRI','SAT','SUN','MON'][i],'',`<span class="day">${23+i}</span><span class="name">OCT</span>`,'date-card')).join('')}${choice('date','any','ANY DAY WORKS','','','wide')}</div>`;case 'time':return `<div class="choices times">${TIMES.map(t=>choice('time',t,t==='other'?'OTHER TIME':t,'','',''+(t==='other'?'wide':''))).join('')}</div>`+(state.time==='other'?field('customTime','What time works for you?','','time'):'');case 'pickup':return field('pickup','Pickup location','Напиши место...','text',300);case 'review':return review();}}
function render(focus=true){if(current==='intro'){app.innerHTML=introHTML;}else if(current==='confirmed'){app.innerHTML=`<section class="success"><div class="eyebrow">ATTEMPT #002</div><h1>IT'S A DATE.</h1><p>Your plan has been received.</p><p class="preparing">DATE #002<br>is being prepared.</p><p>See you soon.</p><div class="status-strip"><div><small>STATUS</small><span class="status-dot"></span>CONFIRMED</div><div><small>TICKET</small>COMING SOON</div></div></section>`;}else{const all=steps(state),index=all.indexOf(current);const [label,title,subtitle]=titles[current];app.innerHTML=`<section class="page"><div class="progress-head"><button class="back" data-action="back">BACK</button><span>${String(index+1).padStart(2,'0')} / ${String(all.length).padStart(2,'0')}</span></div><div class="progress" role="progressbar" aria-label="Invitation progress" aria-valuemin="1" aria-valuemax="${all.length}" aria-valuenow="${index+1}">${all.map((_,i)=>`<span class="${i<=index?'done':''}"></span>`).join('')}</div><div class="step-label">${current==='second'?`${esc(activity(state,'main'))} selected.`:label}</div><h1>${title}</h1><p class="subtitle">${subtitle}</p>${content()}<p id="error" class="error" role="alert"></p><div class="actions">${current==='review'?'<button class="text-button" data-edit="main">CHANGE SOMETHING</button>':`<span class="quiet">${competitive(state)&&['main','second'].includes(current)?'Loser buys dessert.':'JUST US. YOUR CALL.'}</span>`}<button class="primary" data-action="${current==='review'?'submit':'next'}">${current==='review'?'LOOKS GOOD':'CONTINUE'}</button></div></section>`;}if(focus){app.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
function showError(message){const el=document.querySelector('#error');if(el)el.textContent=message;const input=app.querySelector('input');if(input){input.setAttribute('aria-invalid','true');input.focus();}}
function go(step){current=step;failed=false;render();}
function select(field,value){state[field]=value;cleanup(state);failed=false;render(false);const selected=[...app.querySelectorAll('[data-field]')].find(el=>el.dataset.field===field&&el.dataset.value===value);selected?.focus({preventScroll:true});}
function next(){const error=validateStep(state,current);if(error)return showError(error);const all=steps(state);go(all[all.indexOf(current)+1]);}
async function submit(){if(busy)return;const invalid=validatePlan(state);if(invalid){go(invalid.step);return showError(invalid.error);}const payload=JSON.stringify(state);if(payload!==lastPayload){submissionId=crypto.randomUUID();lastPayload=payload;}busy=true;app.setAttribute('aria-busy','true');app.querySelectorAll('button,input').forEach(el=>el.disabled=true);const button=app.querySelector('[data-action="submit"]');button.textContent='ONE MOMENT…';document.querySelector('#error').textContent='';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);let response;try{response=await fetch(SUBMISSION_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','X-Submission-ID':submissionId},body:payload,signal:controller.signal,credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer'});}finally{clearTimeout(timer);}const result=await response.json();if(!response.ok||result.ok!==true)throw Error('Delivery failed');Object.assign(state,initialState());lastPayload='';go('confirmed');}catch{failed=true;showError('Something went wrong. Try again.');button.textContent='TRY AGAIN';}finally{busy=false;app.removeAttribute('aria-busy');app.querySelectorAll('button,input').forEach(el=>el.disabled=false);}}
app.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||busy)return;if(button.id==='begin')return go('main');if(button.dataset.field)return select(button.dataset.field,button.dataset.value);if(button.dataset.edit)return go(button.dataset.edit);if(button.dataset.action==='next')return next();if(button.dataset.action==='back'){const all=steps(state);return go(all[all.indexOf(current)-1]);}if(button.dataset.action==='submit')submit();});
app.addEventListener('input',event=>{if(!(event.target instanceof HTMLInputElement))return;state[event.target.name]=event.target.value;cleanup(state);event.target.removeAttribute('aria-invalid');document.querySelector('#error').textContent='';});
app.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target instanceof HTMLInputElement){event.preventDefault();next();}});
