import {initialState,validatePlan,hasDrive,activity,displayDate,displayTime,normalize,MUSIC} from '../model.js';
const recent=new Map();
const localLimits=new Map();
const json=(status,data,origin)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...(origin?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{})}});
export function validateRequest(value){if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid data');const keys=Object.keys(initialState());if(Object.keys(value).length!==keys.length||Object.keys(value).some(k=>!keys.includes(k)))throw Error('Unexpected fields');for(const key of keys){if(typeof value[key]!=='string'||value[key].length>(key==='pickup'?300:120)||/[\u0000-\u001f\u007f]/.test(value[key]))throw Error('Invalid field');}const s=Object.fromEntries(keys.map(k=>[k,value[k].trim()]));if((s.mainActivity!=='custom'&&s.mainActivityCustom)||(s.secondActivity!=='custom'&&s.secondActivityCustom)||(s.time!=='other'&&s.customTime)||(!hasDrive(s)&&s.music))throw Error('Stale fields');if(validatePlan(s))throw Error('Incomplete plan');return s;}
export function telegramMessage(s,now=new Date()){const rows=['NEW DATE — ATTEMPT #002','MAIN EVENT\n'+activity(s,'main')];if(s.mainActivity==='custom')rows.push('MAIN SOURCE\nHer idea');if(s.secondActivity!=='none'){rows.push('SECOND STOP\n'+activity(s,'second'));if(s.secondActivity==='custom')rows.push('SECOND SOURCE\nHer idea');}rows.push('DATE\n'+displayDate(s.date),'TIME\n'+displayTime(s));if(hasDrive(s))rows.push('MUSIC\n'+(s.music==='your-bluetooth'?'Her Bluetooth':MUSIC.find(x=>x[0]===s.music)[1]));rows.push('PICKUP\n'+s.pickup,'STATUS\nCONFIRMED','Submitted:\n'+new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Almaty'}).format(now)+' (Asia/Almaty)');return rows.join('\n\n');}
async function readLimited(request){if(Number(request.headers.get('Content-Length'))>4096)throw Error('Body too large');const reader=request.body?.getReader();if(!reader)throw Error('Missing body');let total=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>4096){await reader.cancel();throw Error('Body too large');}chunks.push(value);}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return JSON.parse(new TextDecoder().decode(bytes));}
async function allowedRate(request,env){const key=request.headers.get('CF-Connecting-IP')||'local';if(env.RATE_LIMITER)return (await env.RATE_LIMITER.limit({key})).success;const now=Date.now();for(const [ip,entry] of localLimits)if(entry.expires<now)localLimits.delete(ip);const entry=localLimits.get(key)||{count:0,expires:now+60000};entry.count++;if(localLimits.size<1000||localLimits.has(key))localLimits.set(key,entry);return entry.count<=5;}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname!=='/api/confirm')return env.ASSETS?env.ASSETS.fetch(request):new Response('Not found',{status:404});const origin=request.headers.get('Origin');const allowedOrigin=env.ALLOWED_ORIGIN||url.origin;if(!origin||origin!==allowedOrigin)return json(403,{ok:false},null);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':origin,'Vary':'Origin','Access-Control-Allow-Methods':'POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, X-Submission-ID','Access-Control-Max-Age':'600'}});if(request.method!=='POST')return json(405,{ok:false},origin);if(request.headers.get('Content-Type')?.split(';')[0].trim()!=='application/json')return json(415,{ok:false},origin);const id=request.headers.get('X-Submission-ID')||'';if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))return json(400,{ok:false},origin);
try{if(!await allowedRate(request,env))return json(429,{ok:false},origin);}catch{return json(503,{ok:false},origin);}let state;try{state=validateRequest(await readLimited(request));}catch{return json(400,{ok:false},origin);}if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID)return json(503,{ok:false},origin);
const now=Date.now();for(const [key,entry] of recent)if(entry.expires<now)recent.delete(key);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(state)));const fingerprint=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');const existing=recent.get(id);if(existing){if(existing.fingerprint!==fingerprint)return json(409,{ok:false},origin);const ok=await existing.promise;return json(ok?200:502,{ok},origin);}if(recent.size>=1000)return json(503,{ok:false},origin);
const delivery=(async()=>{try{const response=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/sendMessage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:env.TELEGRAM_CHAT_ID,text:telegramMessage(state),link_preview_options:{is_disabled:true}}),signal:AbortSignal.timeout(12000)});const result=await response.json();return response.ok&&result.ok===true;}catch{return false;}})();recent.set(id,{fingerprint,promise:delivery,expires:now+600000});const ok=await delivery;if(!ok)recent.delete(id);return json(ok?200:502,{ok},origin);
}};
